title:            Martin Feckie - Code Nurse
description:      Musings on coding and humanity
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://mfeckie.github.io

# Owner/author information
owner:
  name:           Martin Feckie
  avatar:         avatar.png
  bio:            "Code Nurse @ ThoughtWorks"
  email:          mfeckie@thoughtworks.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: mfeckie
  github: mfeckie
  stackexchange: https://stackexchange.com/users/2075883
  linkedin: martin-feckie-1986023a

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-63270316-1

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Perth
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll_inline_highlight

sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "_drafts"]
